export default [
    { id: 1, title: "Bern" },
    { id: 2, title: "CityLake" },
    { id: 3, title: "Mountain" },
    { id: 4, title: "Mountain" },
    { id: 5, title: "Zurich" },
    { id: 6, title: "Cow" },
    { id: 7, title: "Luzern" },
    { id: 8, title: "Mountain" },
    { id: 9, title: "Train" },
    { id: 10, title: "Mountain" },
    { id: 11, title: "Zurich" },
    { id: 12, title: "Mountain" },
    { id: 13, title: "Luzern" },
    { id: 14, title: "Zurich" },
    { id: 15, title: "Vespa" },
    { id: 16, title: "Road" },
    { id: 17, title: "Lake" },
    { id: 18, title: "Village" },
    { id: 19, title: "Mountain" },
    { id: 20, title: "Mountain" },
    { id: 21, title: "Mountain" },
  ];